spring:
  application:
    name: artists-service
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    url: jdbc:h2:mem:artists
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db.migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8086
